### ISSUE TITLE
proofs of absence in client.proto

### ISSUE THREAD

**Issue by diracdeltas** [yahoo/coname#10]
`LookupProof` should generalize to proofs of absence, right? Does the message structure need to be different to handle absence proofs?

**Comment by andres-erbsen** [comment]
On July 21, 2015 3:36:10 PM PDT, Yan Zhu <notifications@github.com> wrote:
>`LookupProof` should generalize to proofs of absence, right? Does the
>message structure need to be different to handle absence proofs?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/yahoo/coname/issues/10

The contents of the tree proof will indicate absence and profile will be nil. So no structure change.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by diracdeltas** [comment]
I think that is true for a sparse tree but not necessarily for a prefix tree. See https://github.com/google/e2e-key-server/pull/5/files

**Comment by andres-erbsen** [comment]
Hmm. We really don't want a tree where a proof of absence would require the server to reveal another username. I hope this is not necessary, or if it is for that particular prefix tree, we can move to a new one. Anything saner than that can be encapsulated in tree proof. Or was there something else you were pointing to?

**Comment by diracdeltas** [comment]
I think you only need to reveal `profile_hash` not the actual username.

cc @daniel-ziegler who has thought about this more

**Comment by diracdeltas** [comment]
never mind the comment above re: revealing usernames

**Comment by andres-erbsen** [comment]
https://github.com/yahoo/coname/blob/b988978431d34959165fcf85c8c5dc3b22faeaaa/server/lookup.go#L83 seems to be working fine with the current structure.
