### ISSUE TITLE
Mocking time

### ISSUE THREAD

**Issue by andres-erbsen** [yahoo/coname#11]
Several hours of developer time were just spent debugging a livelocked test. Oh well. We really should remove all time-dependence from the testing -- is https://godoc.org/github.com/facebookgo/clock the way go, or does anybody have positive experience with some other library?

**Comment by diracdeltas** [comment]
pinging @coruus @dmitris

**Comment by andres-erbsen** [comment]
`facebookgo/clock` does not support timer.Reset. So we either need to fork and implement it ourselves, or find a different library.

**Comment by andres-erbsen** [comment]
https://godoc.org/github.com/andres-erbsen/clock seems to be working fine so far :)
