### ISSUE TITLE
Postponed renames

### ISSUE THREAD

**Issue by andres-erbsen** [yahoo/coname#3]
This issue is for tracking planned renames of packages and interfaces.

- `server` -> `keyserver`, because `server` is really not descriptive.
- `server.VerifierBroadcast`, `server.WaitingRoom` -> separate packages in `server/internal/` [(internal folder spec)](https://docs.google.com/document/d/1e8kOo3r51b2BWtTs_1uADIA5djfXhPT36s6eHVRIvaU/edit)
- `coname` -> `e2eks` when it is known what the final name will be AND that the coname design will be used to implement that.

**Comment by diracdeltas** [comment]
what about `leeks` -> Lightweight End-to-End Key Server

I can't think of other words that start with L but there are probably some.

**Comment by diracdeltas** [comment]
`arboretum` since we're making a bunch of trees?

**Comment by andres-erbsen** [comment]
`Thing_PreserveEncoding` -> `EncodedThing`

**Comment by andres-erbsen** [comment]
Another name proposal: `donkeys`.

**Comment by andres-erbsen** [comment]
`cnclient` -> `cnlookup`, `cnmgr` as in dename?
