### ISSUE TITLE
rename the main directory in https://github.com/yahoo/coname/tree/master/keyserver/main

### ISSUE THREAD

**Issue by dmitris** [yahoo/coname#41]
I suggest to rename the subdirectory "main" in keyserver/main to something more descriptive and appropriate for the name of generated library - so that you could use the 'regular' `go install -v github.com/yahoo/coname/keyserver/somethingdescriptive" command and not end up with executable "main" (or have to fall back on `go build` command).

Also, now after running `go get -v github.com/yahoo/coname`, you do get an executable "main" in your GOPATH/bin (or GOBIN):
```
$ GOPATH=/tmp/yago go get -v -u -t -x github.com/yahoo/coname/...
$ ls -l /tmp/yago/bin
total 97376
-rwxr-xr-x  1 dmitris users  11555548 Jan 11 21:53 cnclient
-rwxr-xr-x  1 dmitri users  11218892 Jan 11 21:53 deploy
-rwxr-xr-x  1 dmitris users  16354428 Jan 11 21:53 main
-rwxr-xr-x  1 dmitris users 10723040 Jan 11 21:53 protoc-gen-coname
```

**Comment by daniel-ziegler** [comment]
@dmitris, I'll let you review and merge #42 (and maybe fix build/deploy scripts).
