### ISSUE TITLE
verifier vs ratifier terminology

### ISSUE THREAD

**Issue by diracdeltas** [yahoo/coname#7]
In client.proto, `verifier` and `ratifier` seem to be used interchangeably. If they actually are the same thing, let's use one or the other.

**Comment by andres-erbsen** [comment]
I agree and I think we should decide on one tomorrow. They were distinct when we were to have both verifiers and auditors, but both of them ratified.

**Comment by andres-erbsen** [comment]
we seem to have silently converged on using "verifier" for everybody who signs epoch heads.
