### ISSUE TITLE
s/version/counter

### ISSUE THREAD

**Issue by diracdeltas** [yahoo/coname#8]
in https://github.com/yahoo/coname/blob/master/proto/client.proto#L111, `version` is confusing; for instance, it could also be used to refer to API version. I think `counter` is what you mean.

**Comment by andres-erbsen** [comment]
Counter sounds to me like it would increase by exactly by one each time. And the public Spanner paper, for example, uses the language of versions for database entries.

**Comment by diracdeltas** [comment]
Yeah, that's a good point.
