### ISSUE TITLE
signature over LookupProof

### ISSUE THREAD

**Issue by diracdeltas** [yahoo/coname#9]
shouldn't `LookupProof` be signed by the keyserver so that it can be used by the client to prove that a keyserver is misbehaving? Ex: if a keyserver returns a malicious tree proof and the client detects this, it can be used as evidence of compromise.

**Comment by andres-erbsen** [comment]
On July 21, 2015 3:33:31 PM PDT, Yan Zhu <notifications@github.com> wrote:
>shouldn't `LookupProof` be signed by the keyserver so that it can be
>used by the client to prove that a keyserver is misbehaving? Ex: if a
>keyserver returns a malicious tree proof and the client detects this,
>it can be used as evidence of compromise.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/yahoo/coname/issues/9

The keyserver is one of the ratifiers and thus signs the tree summary anyway. And signing each and every update would cause CPU load.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by diracdeltas** [comment]
I would a comment noting that the client MUST not accept a proof unless the keyserver is one of the ratifiers

**Comment by andres-erbsen** [comment]
On July 21, 2015 3:39:50 PM PDT, Yan Zhu <notifications@github.com> wrote:
>I would a comment noting that the client MUST not accept a proof unless
>the keyserver is one of the ratifiers
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/yahoo/coname/issues/9#issuecomment-123500091

Sure, why not, but if the verifiers are good then it does not matter, right?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
